"""empty message

Revision ID: b2fe38f2a016
Revises: df93adbc4c77
Create Date: 2024-05-17 00:24:02.626082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fe38f2a016'
down_revision = 'df93adbc4c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eats', schema=None) as batch_op:
        batch_op.alter_column('eats_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eats', schema=None) as batch_op:
        batch_op.alter_column('eats_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
