"""empty message

Revision ID: df93adbc4c77
Revises: 
Create Date: 2024-05-17 00:21:57.819901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df93adbc4c77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=10), nullable=False))
        batch_op.alter_column('eats_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eats', schema=None) as batch_op:
        batch_op.alter_column('eats_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('test')

    # ### end Alembic commands ###
